CREATE TABLE coffee
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(255),
    price INTEGER,
    PRIMARY KEY (id)
);

-- 단건 추가
INSERT INTO coffee(id, name, price) VALUES (default, '아메리카노', 4100)
;

-- 여러건 추가
INSERT INTO coffee(id, name, price)
VALUES (default, '라떼', 4600),
       (default, '모카', 5100),
       (default, '오늘의 커피', 3800)
;